server:
  port: 8050
  # ssl:
  #   enabled: true
  #   key-store: file:/${KEY_RELATIVE_PATH}
  #   key-store-password: ${KEY_PASSWORD}
  #   key-store-type: PKCS12
  #   key-alias: ${KEY_ALIAS}
  forward-headers-strategy: framework 
  servlet:
    session:
      cookie:
        secure: false
spring:
  application:
    name: msvc-security
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://10.255.252.4:1433;encrypt=true;trustServerCertificate=true;databaseName=edemco_pruebas
    username: sa
    password: Edemco2017.
  jpa:
    hibernate:
      ddl-auto: update
    database: sqlserver
    database-platform: org.hibernate.dialect.SQLServerDialect
  security:
    oauth2:
      client:
        registration:
          azure:
            provider: azure
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "https://${IP_SERVER}:8080/login/oauth2/code/azure"
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/aed8c5fc-8a52-4ad1-819d-93b2e9c562b4/v2.0
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.web: DEBUG
api:
  secret: ${SECRET_KEY}

eureka:
  instance:
    hostname: ${IP_SERVER}
  client:
    service-url:
      defaultZone: https://${IP_SERVER}:8761/eureka/