server:
  port: 8888
  # ssl:
  #   enabled: true
  #   key-store: file:/${KEY_RELATIVE_PATH}
  #   key-store-password: ${KEY_PASSWORD}
  #   key-store-type: PKCS12
  #   key-alias: ${KEY_ALIAS}

spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations

management:
  endpoints:
    web:
      exposure:
        include: health, info, *
  endpoint:
    health:
      show-details: always
  health:
    enabled: true